# Generated by Django 4.1 on 2022-08-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Сайт, телеграмм бот, реклама, другое', max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проекта',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000, verbose_name='Название')),
                ('amount_client', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Сумма для клиента')),
                ('amount_planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Сумма планируемых затрат')),
                ('amount_actual_costs', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Сумма фактических затрат')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_planned_completion', models.DateField(auto_now_add=True)),
                ('date_actual_completion', models.DateField(auto_now_add=True)),
                ('type_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.typeprojects', verbose_name='Тип проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-title'],
            },
        ),
    ]
